variable "name" {
  description = "Base name for resources"
  type        = string
}

variable "vpc_id" {
  description = "VPC id where bastion will be placed"
  type        = string
}

variable "public_subnet_ids" {
  description = "List of public subnet ids for the ASG"
  type        = list(string)
}

variable "key_pair_name" {
  description = "Key pair name generated by vpc module"
  type        = string
}

variable "private_key_pem" {
  description = "Private key PEM content generated by VPC module (sensitive)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "newrelic_api_key" {
  description = "New Relic Infrastructure license / API key"
  type        = string
  sensitive   = true
  default     = ""
}

variable "newrelic_account_id" {
  description = "New Relic Account ID"
  type        = string
  default     = ""
}

variable "region" {
  type    = string
  default = "eu-west-2"
}

